# DO NOT DEPLOY THIS APP
# You should be  deploying flightdb/app/frontend, as it already
# does everything. Only deploy this app if you want a realtime
# maps view without any flightdb stuff.
do_not_deploy_this_app: deploy_flightdb_app_frontend_instead

service: pifrontend
runtime: go
api_version: go1
instance_class: F1

handlers:
- url: /static
  static_dir: static
- url: /
  script: _go_app
- url: /comp
  script: _go_app
- url: /json
  script: _go_app

- url: /comp2
  script: _go_app
