# DO NOT DEPLOY THIS APP
# If you are deploying flightdb/ui, as it already does everything.
# Only deploy this app if you want a realtime maps view without
# any flightdb stuff.

application: serfr0-fdb
module: pifrontend
version: one
runtime: go
api_version: go1
instance_class: F1

handlers:
- url: /static
  static_dir: static
- url: /
  script: _go_app
- url: /comp
  script: _go_app
- url: /json
  script: _go_app

- url: /comp2
  script: _go_app
